apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
spec:
  version: nightly
  microcks:
    url: microcks.m.minikube.local
  keycloak:
    url: keycloak.m.minikube.local
  features:
    async:
      enabled: true
      kafka:
        url: kafka.m.minikube.local
      #sqs:
      #  region: eu-west-3
      #  credentialsSecretRef:
      #    name: aws-credentials
