apiVersion: microcks.io/v1alpha1
kind: Microcks
metadata:
  name: microcks
spec:
  microcks:
    image:
      registry: quay.io
      repository: microcks/microcks
  postman:
    image:
      registry: quay.io
      repository: microcks/microcks-postman-runtime
      tag: 0.7.0
  keycloak:
    image:
      registry: quay.io
      repository: keycloak/keycloak
      tag: 26.0.0
    postgresImage:
      registry: docker.io
      repository: library/postgres
      tag: 16.3-alpine
  mongodb:
    image:
      registry: docker.io
      repository: library/mongo
      tag: 4.4.29
  features:
    async:
      image:
        registry: quay.io
        repository: microcks/microcks-async-minion