# To skip CRD installation (Helm v3 installs files under crds/ automatically), use --skip-crds
nameOverride: ""
fullnameOverride: ""

image:
  repository: quay.io/microcks/microcks-operator
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []

replicaCount: 1

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
